# Generated by Django 5.0.14 on 2026-06-06 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('WALLPAPER', 'Wallpaper'), ('THUMBNAIL', 'Thumbnail'), ('SOCIAL', 'Social / Newsfeed'), ('DOCUMENT', 'Document'), ('CUSTOM', 'Custom')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resize Preset',
                'verbose_name_plural': 'Resize Presets',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResizeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Upload'), ('URL', 'URL')], max_length=10)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('original_size', models.PositiveIntegerField(default=0)),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_format', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resize_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resize Job',
                'verbose_name_plural': 'Resize Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResizeOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('output_key', models.CharField(max_length=500)),
                ('output_url', models.URLField(blank=True, max_length=2000)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='images.resizejob')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.resizepreset')),
            ],
            options={
                'verbose_name': 'Resize Output',
                'verbose_name_plural': 'Resize Outputs',
                'ordering': ['created_at'],
            },
        ),
    ]
