# Generated by Django 5.0.14 on 2026-06-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resizepreset',
            name='is_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resizepreset',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resizepreset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resizepreset',
            name='category',
            field=models.CharField(choices=[('WALLPAPER', 'Wallpaper'), ('THUMBNAIL', 'Thumbnail'), ('SOCIAL', 'Social / Newsfeed'), ('LOGO', 'Logo'), ('ICON', 'Icon'), ('DOCUMENT', 'Document'), ('CUSTOM', 'Custom')], db_index=True, max_length=20),
        ),
    ]
