# Generated by Django 5.0.14 on 2026-06-06
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_resizepreset_is_system_resizepreset_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resizepreset',
            old_name='is_system',
            new_name='is_predefined',
        ),
    ]
